# Chapter 2: Variables and Basic Data Structures
by [Arief Rahman Hakim](https://github.com/ahman24)


## Solutions on Problems
There are only a few of them I worked on.

### Q1 and Q2
1. Assign the value 2 to the variable x and the value 3 to the variable y. Clear just the variable x.
2. Write a line of code that generates the following error:

In [1]:
x = 2
y = 3

print('x is',x,'y is',y)

x is 2 y is 3


In [2]:
# delete var x
del x
print(x)

NameError: name 'x' is not defined

### Q3 and Q4
Let x = 10 and y = 3. Write a line of code that will make each of the following assignments.

* u = x + y
* v = xy
* w = x/y
* z = sin(x)
* r = 8sin(x)
* s = 5sin(xy)
* p = x**y

Then show all variables stored on memory

In [9]:
import math
x = 10
y = 3

u = x + y
v = x*y
w = x/y
z = math.sin(x)
r = 8*math.sin(x)
s = 5*math.sin(x*y)
p = x**y

%whos

Variable   Type      Data/Info
------------------------------
math       module    <module 'math' (built-in)>
os         module    <module 'os' from 'D:\\Anaconda\\lib\\os.py'>
p          int       1000
r          float     -4.352168887114958
s          float     -4.940158120464309
sys        module    <module 'sys' (built-in)>
u          int       13
v          int       30
w          float     3.3333333333333335
x          int       10
y          int       3
z          float     -0.5440211108893698


### Q5
Assign string ‘123’ to the variable S. Convert the string into a float type and assign the output to the variable N. Verify that S is a string and N is a float using the type function.

In [12]:
S = '123'
N = float(S)
print('Var S is', type(S), 'Var N is ', type(N))

Var S is <class 'str'> Var N is  <class 'float'>


### Q6
Assign the string ‘HELLO’ to the variable s1 and the string ‘hello’ to the variable s2. Use the == operator to show that they are not equal. Use the == operator to show that s1 and s2 are equal if the lower method is used on s1. Use the == operator to show that s1 and s2 are equal if upper method is used on s2.

In [20]:
s1 = 'HELLO'
s2 = 'hello'

print(s1 == s2)
print(s1.lower() == s2)
print(s1 == s2.upper())


False
True
True


### Q8 and Q9
Check if ‘Python’ is in ‘Python is great!’.
Then, Get the last word ‘great’.

In [23]:
txt1 = 'Python'
txt2 = 'Python is great!'

print(txt1 in txt2)
print(txt2[10:16])

True
great!


### Q13 and Q14
Create one tuple with element ‘One’, 1 and assign it to tuple_a. Then, get the 2nd element in the tuple_a in problem 13.

In [26]:
tuple_a = ('One', 1)
print(type(tuple_a))
tuple_a[1]

<class 'tuple'>


1

### Q15
Get the unique element from (2, 3, 2, 3, 1, 2, 5).

In [28]:
array = (2, 3, 2, 3, 1, 2, 5)
unique = set(array)
print(unique)

{1, 2, 3, 5}


### Q16
Assign (2, 3, 2) to set_a, and (1, 2, 3) to set_b. Get the following:
* union of set_a and set_b
* intersection of set_a and set_b
* difference of set_a to set_b using difference method

In [32]:
set_a = set([2,3,2])
set_b = set([1,2,3])

print(set_a.union(set_b))
print(set_a.intersection(set_b))
print(set_a.difference(set_b))

{1, 2, 3}
{2, 3}
set()


### Q17 and Q18
Create a dictionary that has the keys ‘A’, ‘B’, ‘C’ with values ‘a’, ‘b’, ‘c’ individually. Print all the keys in the dictionary. Then, check if key ‘B’ is in the dictionary defined in problem 17.

In [40]:
dictionary = {'A':'a', 'B' : 'b', 'C' : 'c'}
print(dictionary)
print(dictionary.keys())
print('B' in dictionary.keys())
print(dictionary.values())

{'A': 'a', 'B': 'b', 'C': 'c'}
dict_keys(['A', 'B', 'C'])
True
dict_values(['a', 'b', 'c'])


### Q29
Generate an array with size 100 evenly spaced between -10 to 10 using linspace function in Numpy.

In [49]:
import numpy as np

array = np.linspace(-10, 10, num=100)
print('Length is', len(array))
print('head is', array[:5])
print('tail is', array[-5:])

Length is 100
head is [-10.          -9.7979798   -9.5959596   -9.39393939  -9.19191919]
tail is [ 9.19191919  9.39393939  9.5959596   9.7979798  10.        ]


### Q31
Create an array,

$y=$ $\begin{bmatrix}3 & 5 & 3\\5 & 2 & 8 \\3 & 5 & 9\end{bmatrix}$

then, calculate the transpose of the array.


In [53]:
y = np.array([[3,5,3], [5,2,8], [3,5,9]])
print('Array y is \n', y,'\n')
print('Transpose of y is \n', y.T)

Array y is 
 [[3 5 3]
 [5 2 8]
 [3 5 9]] 

Transpose of y is 
 [[3 5 3]
 [5 2 5]
 [3 8 9]]


### Q32 and Q33
Create a zero array with size (2, 4). Then, change the 2nd column in the above array to 1

In [55]:
array = np.zeros((2,4))
print('The array is \n', array)

# Change the 2nd column to 1
array[1,:] = 1
print('The modified array is now \n', array)

The array is 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
The modified array is now 
 [[0. 0. 0. 0.]
 [1. 1. 1. 1.]]


### Q34
Write a cell magic to clear all the variables in the Jupyter notebook

In [58]:
%reset
%whos

Interactive namespace is empty.
