# Chapter 3: Functions
by [Arief Rahman Hakim](https://github.com/ahman24)


## Solutions on Problems
There are only a few of them I worked on.

### Q2
Write a function my_checker_board(n), where the output $m$ is an $n×n$ array with the following form:

$m = $ $\begin{bmatrix}1 & 0 & 1 & 0 & 1\\0 & 1 & 0 & 1 & 0\\1 & 0 & 1 & 0 & 1\\0 & 1 & 0 & 1 & 0\\1 & 0 & 1 & 0 & 1\end{bmatrix}$


In [1]:
import numpy as np

def create_checker_board(n):
    board = np.zeros((n,n), dtype=int)
    
    # seq[start:end:step]
    board[::2, ::2] = 1
    board[1::2, 1::2] = 1

    return board

n= 6
print(create_checker_board(n))

[[1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]]


### Q4
Write a function *my_split_matrix(m)*, where $m$ is an array, the output is a list *m1 x m2* where *m1* is the left half of *m*, and *m2* is the right half of *m*. In the case where there is an odd number of columns, the middle column should go to *m1*. Assume that *m* has at least two columns.

In [2]:
a = np.zeros((3,4))
a[:, 2:]

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
def my_split_matrix(m):
    _,n_col = m.shape

    if n_col%2 ==0:
        n_slice = int(n_col / 2)
    elif n_col%2 !=0:
        n_slice = n_col // 2 + 1
    
    m1 = m[:, :n_slice]
    m2 = m[:, n_slice:]
    return m1, m2

print('For even n_col,')
m = np.zeros((4,4))
m1,m2 = my_split_matrix(m)
print(m1)
print(m2)

print('\n For odd n_col,')
m = np.zeros((4,5))
m1,m2 = my_split_matrix(m)
print(m1)
print(m2)

For even n_col,
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

 For odd n_col,
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


### Q6
Write a function my_n_odds(a), where a is a one-dimensional array of floats and the output is the number of odd numbers in a.

In [4]:
def my_n_odds(a):
    #apply modulus
    n = a.size
    odd = a % 2
    n_odd = odd.sum()
    n_even = n - n_odd

    return n_odd, n_even

a = np.linspace(1,10,10)
n_odd, n_even = my_n_odds(a)
print(f'For matrix a, \n \n a = {a} \n \n there are {int(n_odd)} odd numbers and {int(n_even)} numbers')

For matrix a, 
 
 a = [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] 
 
 there are 5 odd numbers and 5 numbers
