# Chapter 4: Branching Statements
by [Arief Rahman Hakim](https://github.com/ahman24)


## Solutions on Problems
There are only a few of them I worked on.

### Q1
Write a function `my_tip_calc(bill, party)`, where `bill` is the total cost of a meal and `party` is the number of people in the group. The tip should be calculated as 15% for a party strictly less than six people, 18% for a party strictly less than eight, 20% for a party less than 11, and 25% for a party 11 or more. A couple of test cases are given below.

In [4]:
def my_tip_calc(bill, n):
    if n <= 6:
        tip = 0.15 * bill
    elif 6 < n <= 8:
        tip = 0.18 * bill
    elif 8 < n < 11:
        tip = 0.20 * bill
    else:
        tip = 0.25 * bill
    
    return tip

n_3 = my_tip_calc(109.29,3)
n_7 = my_tip_calc(109.29,7)
n_9 = my_tip_calc(109.29,9)
n_12 = my_tip_calc(109.29,12)

n_3 = round(n_3,3)
n_7 = round(n_7,3)
n_9 = round(n_9,3)
n_12 = round(n_12,3)

table = {'3':n_3, '7':n_7, '9':n_9, '12':n_12}
table

{'3': 16.393, '7': 19.672, '9': 21.858, '12': 27.323}

### Q3
Consider a triangle with vertices at `(0,0), (1,0), and (0,1)`. Write a function `my_inside_triangle(x,y)` where the output is the string `‘outside’` if the point `(x,y)` is outside of the triangle, `‘border’` if the point is exactly on the border of the triangle, and `‘inside’` if the point is on the inside of the triangle

In [5]:
class check_triangle:
    def __init__(self, x, y):
        # (x,y)
        self.point1 = (0,0)
        self.point2 = (1,0)
        self.point3 = (0,1)
        self.point_to_check = (x,y)
        self.check()

    def calc_area(self, point1, point2, point3):
        # area = 1/2 * abs(x1(y2-y3) + x2(y3-y1) + x3(y1-y2))
        area = 1/2 * abs((point1[0] * (point2[1] - point3[1]) + point2[0] * (point3[1] - point1[1]) + point3[0] * (point1[1] - point2[1])))
        return area

    def check(self):
        # triangle area
        self.area = self.calc_area(self.point1, self.point2, self.point3)

        # mini triangles made by point_to_check
        area1 = self.calc_area(self.point_to_check, self.point2, self.point3)
        area2 = self.calc_area(self.point_to_check, self.point1, self.point3)
        area3 = self.calc_area(self.point_to_check, self.point1, self.point2)
        area_total = area1 + area2 + area3

        if area1 or area2 or area3 == 0.0:
            self.result = 'border'
        elif area_total == self.area:
            self.result = 'inside'
        elif area_total > area:
            self.result = 'outside'

triangle = check_triangle(0.5, 0.5)
print(f'For {triangle.point_to_check}, it is located in {triangle.result}')

triangle = check_triangle(0.25, 0.25)
print(f'For {triangle.point_to_check}, it is located in {triangle.result}')

triangle = check_triangle(5, 5)
print(f'For {triangle.point_to_check}, it is located in {triangle.result}')

For (0.5, 0.5), it is located in border
For (0.25, 0.25), it is located in border
For (5, 5), it is located in border


### Q4
Write a function `my_make_size10(x)`, where x is an array and output is the first `10 elements` of `x` if `x` has more than 10 elements, and output is the array `x` padded with enough zeros to make it length 10 if `x` has less than 10 elements.

In [6]:
import numpy as np

def my_make_size10(x):
    length = x.size
    if length > 10:
        return print(x[:10])
    else:
        to_append = 10 - length
        array_zeros = np.zeros((to_append,1))
        x = np.append(x,array_zeros)
        return print(x[:10])

print(f'If the array is bigger than [10,1], return the first [:10] of the array')
print(f'For array as follows,')
array1 = np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
print(array1)
print(f'\nReturn,')
my_make_size10(array1)

print(f'\nIf the array is smaller than [10,1], add zeros so that the size is [10:1], then return the array')
print(f'For array as follows,')
array2 = np.array([1,1,3])
print(array2)
print(f'\nReturn,')
my_make_size10(array2)


If the array is bigger than [10,1], return the first [:10] of the array
For array as follows,
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

Return,
[1 1 1 1 1 1 1 1 1 1]

If the array is smaller than [10,1], add zeros so that the size is [10:1], then return the array
For array as follows,
[1 1 3]

Return,
[1. 1. 3. 0. 0. 0. 0. 0. 0. 0.]


### Q7
Most engineering systems have redundancy. That is, an engineering system has more than is required to accomplish its purpose. Consider a nuclear reactor whose temperature is monitored by three sensors. An alarm should go off if any two of the sensor readings disagree. 
Write a function `my_nuke_alarm(s1,s2,s3)` where `s1, s2, and s3` are the temperature readings for `sensor 1, sensor 2, and sensor 3`, respectively. The output should be the string `‘alarm!’` if any two of the temperature readings disagree by strictly more than `10 degrees` and `‘normal’` otherwise.

In [7]:
def my_nuke_alarm(sensor):
    max_value = sensor.max()
    min_value = sensor.min()
    dif = max_value - min_value

    if dif >= 10:
        return print("Alarm!")
    else:
        return print('Normal')

sensor_param1 = np.array([100,30,40]) 
print(f'For sensor reading as follows,')
print(sensor_param1)
print(f'The function returns,') 
my_nuke_alarm(sensor_param1)

sensor_param2 = np.array([100,95,93]) 
print(f'\nFor sensor reading as follows,')
print(sensor_param2)
print(f'The function returns,') 
my_nuke_alarm(sensor_param2)

For sensor reading as follows,
[100  30  40]
The function returns,
Alarm!

For sensor reading as follows,
[100  95  93]
The function returns,
Normal
