# Chapter 5: Iteration
by [Arief Rahman Hakim](https://github.com/ahman24)


## Solutions on Problems
There are only a few of them I worked on.

### Q2
Write a function `my_max(x)` to return the maximum (largest) value in `x`. Don’t use the built-in Python function max.

In [1]:
def my_max(x):
    max = x[1]
    for i in range(len(x)):
        if x[i] > max:
            max = x[i]    
    return max

array = [1, 2, 3]
my_max(array)

3

### Q3
Write a function `my_n_max(x, n)` to return a list consisting of the `n largest elements of x`. You may use Python’s max function. You may also assume that `x` is a one-dimensional list with no duplicate entries, and that `n` is strictly positive integer smaller than the length of `x`

In [2]:
def my_n_max(x,n):
    mx = []
    for i in range(n):
        mx.append(max(x))
        x.remove(mx[i])
    return mx

x = [7, 9, 10, 5, 8, 3, 4, 6, 2, 1]
my_n_max(x,2)

[10, 9]

### Q4
Let `m` be a matrix of positive integers. Write a function `my_trig_odd_even(m)` to return an `array q`, where `q[i, j] = sin (m[i, j]) if m[i, j] is even`, and `q[i, j] = cos (m[i, j]) if m[i, j] is odd`.

In [3]:
import math
import numpy as np

def my_trig_odd_even(m):
    n_row, n_col = m.shape
    q = np.zeros((n_row, n_col))
    for row in range(n_row):
        for col in range(n_col):
            if m[row, col] % 2 == 0:
                q[row, col] = math.sin(m[row,col])
            else:
                q[row, col] = math.cos(m[row,col])
    
    return q

P = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
a = my_trig_odd_even(P)
a

array([[ 0.54030231,  0.90929743, -0.9899925 , -0.7568025 ],
       [ 0.28366219, -0.2794155 ,  0.75390225,  0.98935825]])

### Q4
Let `P` be an `m×p array` and `Q` be a `p×n` array. As you will find later in this book, `M=P×Q` is defined as `M[i,j]=∑pk=1P[i,k]⋅Q[k,j]`. 
Write a function `my_mat_mult(P, Q)` that `uses for-loops` to compute M, the matrix product of P and Q. 
Hint: You may need up to three nested for-loops. Do not use the function np.dot.

In [4]:
def my_mat_mult(p,q):
    n_row, n_col = p.shape
    _, n_col_q = q.shape
    m = np.zeros((n_row,n_col_q))
    for row in range(n_row):
        for col in range(n_col_q):
            total = 0
            for row_q in range(n_col):
                total = total + p[row][row_q] * q[row_q][col]
            m[row,col] = total
    return m

P = np.ones((3, 3))
print(f'For the following matrix,')
print(P)
print(f'\nThe P x P will yield,')
value = my_mat_mult(P,P)
print(value)

P = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
Q = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
print(f'\nFor the following matrix,')
print(f'P,')
print(P)
print(f'Q,')
print(Q)
print(f'\nThe P x Q will yield,')
value = my_mat_mult(P,Q)
print(value)

For the following matrix,
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

The P x P will yield,
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]

For the following matrix,
P,
[[1 2 3 4]
 [5 6 7 8]]
Q,
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]

The P x Q will yield,
[[30. 30. 30.]
 [70. 70. 70.]]


### Q5
The interest, `i`, on a principle, `P0`, is a payment for allowing the bank to use your money. Compound interest is accumulated according to the formula,

$Pn=(1+i)P_{n−1}$,

`n` is the compounding period, usually in months or years. 

Write a function `my_saving_plan(P0, i, goal)` where the `output is the number of years` it will take `P0` to become `goal` at `i% interest` compounded annually.

In [5]:
def my_saving_plan(p0, i, pn):
    '''
    p0 : Principal money
    pn : Target money
    i : interest per month
    n : number of months to achieve
    '''
    n = 1
    target = True
    while target:
        pn = (1 + i*n) * p0
        if pn >= goal:
            target = False
        n = n+1
    return n

principal = 10_000_000
interest = 0.04 / 12 # 4% interest per year
goal = 100_000_000

n_months = my_saving_plan(principal, interest, goal)
print(f'To have the money of {principal} grows to {goal}, it takes {n_months} given an interest rate of {round(interest,3)}% per month')

To have the money of 10000000 grows to 100000000, it takes 2701 given an interest rate of 0.003% per month
